export const ADD_TO_CART = 'ADD_TO_CART'
export const SUB_QUANTITY = 'SUB_QUANTITY'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'
export const CHECK_OUT = 'CHECK_OUT'
export const REMOVE_ITEM = 'REMOVE_ITEM'